//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_System.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ID_ORDER { get; set; }
        public Nullable<System.DateTime> DATE_ORDER { get; set; }
        public Nullable<int> ID_CUSTOMER { get; set; }
        public string ProductNname { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> QTE { get; set; }
        public Nullable<int> TPrice { get; set; }
        public Nullable<int> Num { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
