//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_System.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERS
    {
        public string ID { get; set; }
        public string PWD { get; set; }
        public string USER_TYPE { get; set; }
    }
}
